### ISSUE TITLE
Cannot rank files in analyzed

### ISSUE THREAD

**Issue by Sophie-DR** [charlottesirot/elementR#5]
Hi, I cannot change the rank of my files (thus I cannot assess the machine drift)... The arrows appear in each box but I cannot type any number. Is it due to my browser (google chrome)?

![image](https://user-images.githubusercontent.com/30770773/29002504-318d74b0-7aa4-11e7-9f78-31933edb7612.png)

Thank you for your nice package! I'm looking forward to use it fully!

**Comment by charlottesirot** [comment]
Hello Sophie, 

Thanks for reporting. 
Well, it should not be related to the web browser. What is the definition of the screen you used to take this screenshot?

Cheers :)

**Comment by Sophie-DR** [comment]
Hi Charlotte,

Thanks for your fast answer. My resolution is 1290 x 1080.

**Comment by Sophie-DR** [comment]
Did you find what the issue could be? Should I change my resolution to open elementR correctly? To what resolution?

**Comment by charlottesirot** [comment]
Hello Sophie!

I just checked, yes the screen resolution might change the space allowed to write the ranks (we developed the software on larger resolution). To remedy that, just zoom a bit out and then the numbers should appeared. You can let this zoom setting as it or just zoom in again afterwards.

Does it work for you ?

**Comment by Sophie-DR** [comment]
Yes it does work when I zoom in. Thanks!

**Comment by charlottesirot** [comment]
Super !! You are welcome :)

**Comment by Sophie-DR** [comment]
Additional question: what is the optimal resolution you designed the web browser with? It will probably make things much easier if I can adapt my screen to that resolution.

**Comment by Sophie-DR** [comment]
To maybe help further users, I managed to solve the issue of the resolution on my laptop: I was increasing the size of all elements to 150 x but now I am back to 100 x (quite small!) but then elementR can display the ranking correctly. Good to know.
